### ISSUE TITLE
使用pyinstaller编译成exe后，执行会报如下的错误

### ISSUE THREAD

**Issue by mlzboy** [waketzheng/fastapi-cdn-host#1]
(base) c:\dd>xx.exe
Traceback (most recent call last):
  File "importlib\metadata\__init__.py", line 563, in from_name
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xx.py", line 39, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "fastapi_cdn_host\__init__.py", line 8, in <module>
  File "importlib\metadata\__init__.py", line 1008, in version
  File "importlib\metadata\__init__.py", line 981, in distribution
  File "importlib\metadata\__init__.py", line 565, in from_name
importlib.metadata.PackageNotFoundError: No package metadata was found for fastapi_cdn_host
[19984] Failed to execute script 'xx' due to unhandled exception!

**Comment by waketzheng** [comment]
Fixed.
```bash
pip install --upgrade "fastapi-cdn-host>=0.7.4"
```
如果报ERROR: Could not find a version that satisfies。。。的错误，可用这个命令：`pip install -i https://pypi.org/simple --upgrade "fastapi-cdn-host>=0.7.4"`
